// Generated by ts-to-zod
import { z } from "zod";

export const processInfoSchema = z.object({
  app: z.string(),
  pid: z.number(),
  cpuPercent: z.string(),
});

export const diskInfoSchema = z.object({
  device: z.string(),
  mountPoint: z.string(),
  total: z.string(),
  free: z.string(),
  used: z.string(),
  usedPercentage: z.string(),
});

export const metricsSchema = z.object({
  timestamp: z.string(),
  memory: z.object({
    total: z.string(),
    free: z.string(),
    used: z.string(),
    usedPercentage: z.string(),
  }),
  cpu: z.object({
    cores: z.number(),
    used: z.string(),
    available: z.string(),
  }),
  processes: z.array(processInfoSchema),
  disk: z.array(diskInfoSchema),
});
